export const SignupStyled = {
    page: {
      height: "85%",
      width: "90%",
      fontFamily: "Poppins, sans-serif",
      fontStyle: "normal",
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
    },
    welcomeQuotes: {
      height: "18%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
    },
    welcome: {
      color: "#0e1824",
      fontSize: "20px",
      fontWeight: 600,
    },
    quotes: {
      width: "80%",
      color: "#71707e",
      fontSize: "12px",
      fontWeight: 400,
    },
    signupbuttons: {
      marginTop: "4%",
      backgroundColor: "#49c792",
            color: "white",
            textTransform: "none",
            fontFamily: "Poppins, sans-serif",
    },
    tags: {
      display: "flex",
      flexDirection: "column",
      height: "33%",
      justifyContent: "space-between",
    },
    googleSignup: {
      cursor: "pointer",
      fontWeight: 500,
      borderRadius: "4px",
      height: "40px",
      display: "flex",
      width: "100%",
      backgroundColor: "#f8f8f8",
      color: "#353448",
      fontSize: "14px",
      alignItems: "center",
    },
    microsoftSignup: {
      cursor: "pointer",
      fontWeight: 500,
      borderRadius: "4px",
      height: "40px",
      display: "flex",
      width: "100%",
      backgroundColor: "#f8f8f8",
      color: "#353448",
      fontSize: "14px",
      alignItems: "center",
    },
    orHrSignup: {
      display: "flex",
      color: "#71707e",
      alignItems: "center",
      height: "20%",
      justifyContent: "center",
      gap: "0.7rem",
    },
    hrSignup: {
      width: "30%",
      backgroundColor: "#ebebeb",
    },
    icons: {
      width: "25px",
      marginLeft: "7%",
    },
    iconContainer: {
      width: "33%",
      display: "flex",
      alignItems: "center",
    },
    workEmail: {
      color: "#484759",
      display: "flex",
      fontSize: "12px",
      gap: "0.2rem",
      fontWeight: 500,
    },
    bottom: {
      display: "flex",
      flexDirection: "column",
      height: "45%",
      justifyContent: "space-between",
    },
    inputs: {
      width: "100%",
      "&::placeholder": {
        fontFamily: "Poppins, sans-serif",
        fontWeight: 400,
        color: "grey"
      },
      "& .MuiOutlinedInput-root": {
        height: "35px",
        width: "100%",
        borderRadius: "4px",
        overflow: "hidden",
        backgroundColor: "#fff",
        border: "1px solid #ebebeb",
      },
      "& .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
      "& .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
        borderColor: "#b0b0b0",
      },
      "& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
        borderColor: "#3f51b5",
      },
    },
    alreadyLogin: {
      display: "flex",
      fontSize: "13px",
      color: "#71707E",
      cursor: "pointer",
      width: "100%",
      justifyContent: "center",
      gap: "0.7rem",
      height: "22%",
    },
    loginLink: {
      color: "#353448",
      textDecoration: "underline",
      fontWeight: 600,
    },
  };
  